//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseInteractions
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balances
    {
        public int ID { get; set; }
        public int Client { get; set; }
        public string Symbol { get; set; }
        public Nullable<decimal> Shares { get; set; }
    }
}
