//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseInteractions
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookInfo
    {
        public string CRid { get; set; }
        public string asin { get; set; }
        public string guid { get; set; }
        public string lang { get; set; }
        public string title { get; set; }
        public string authors { get; set; }
    }
}
