// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DatabaseInteractions
{
    public partial class Client
    {
        public int Id { get; set; }
        public int ChatId { get; set; }
        public int Subscription { get; set; }

        public virtual Subscription SubscriptionNavigation { get; set; }
    }
}