// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DatabaseInteractions
{
    public partial class Enum
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public int? Category { get; set; }
        public string Name { get; set; }
    }
}