//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseInteractions
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookups
    {
        public string CRid { get; set; }
        public string WordID { get; set; }
        public string BookKey { get; set; }
        public string DicKey { get; set; }
        public string Pos { get; set; }
        public string Usage { get; set; }
        public Nullable<int> Timestamp { get; set; }
    }
}
