//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseInteractions
{
    using System;
    using System.Collections.Generic;
    
    public partial class Words
    {
        public int ID { get; set; }
        public string WordID { get; set; }
        public string Word { get; set; }
        public string Stem { get; set; }
        public string Lang { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> Timestamp { get; set; }
        public string ProfileID { get; set; }
    }
}
