on:
  push:
    branches:
      - 'master'
jobs:
    build-container:
        name: Build container
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up QEMU (for ARM emulation)
          uses: docker/setup-qemu-action@v3
          
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
      
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            
        - name: Build and push to Docker Hub
          uses: docker/build-push-action@v5
          with:
            context: "{{defaultContext}}:BotApi"
            push: true
            platforms: linux/arm64
            tags: uhha/helperbot:latest, uhha/helperbot:${{ github.run_number }}
